// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaRick-REOqMREhM4oXyjgfXuks8W0h0M',
    appId: '1:963781030513:web:918c7b81e32c88b0b421d0',
    messagingSenderId: '963781030513',
    projectId: 'ektfaaorganization',
    authDomain: 'ektfaaorganization.firebaseapp.com',
    storageBucket: 'ektfaaorganization.appspot.com',
    measurementId: 'G-YDHL29R8P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-88ttqnbZrdTkk5iv-kc2fZoE3KmXtFk',
    appId: '1:963781030513:android:ddf74df796163d51b421d0',
    messagingSenderId: '963781030513',
    projectId: 'ektfaaorganization',
    storageBucket: 'ektfaaorganization.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBarXP8tM4shkAP2imA6ex1LhWZQYbrEPc',
    appId: '1:963781030513:ios:de2dbc9d4923d3b0b421d0',
    messagingSenderId: '963781030513',
    projectId: 'ektfaaorganization',
    storageBucket: 'ektfaaorganization.appspot.com',
    iosBundleId: 'com.example.ektfaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBarXP8tM4shkAP2imA6ex1LhWZQYbrEPc',
    appId: '1:963781030513:ios:988c42acded93ff8b421d0',
    messagingSenderId: '963781030513',
    projectId: 'ektfaaorganization',
    storageBucket: 'ektfaaorganization.appspot.com',
    iosBundleId: 'com.example.ektfaa.RunnerTests',
  );
}
